import torch
import logging


log = logging.getLogger(__name__)


class ExpMaxRegistration(object):
    """
    Expectation maximization point cloud registration.

    Parameters
    ----------
    target : torch.Tensor  (X)
        NxD array of target points.
    source : torch.Tensor  (Y)
        MxD array of source points. (TODO: these will be registered to the targets?)
    sigma2 : float, optional
        Initial variance of the Gaussian mixture model.
    max_iterations : int, optional
        Maximum number of iterations.
    tolerance : float, optional
        Tolerance for convergence.
    w : float, optional
        Contribution of the uniform distribution to account for outliers.


    Attributes
    ----------
    transformed_y : torch.Tensor
        MxD array of transformed source points.
    sigma2 : float
        Variance of the Gaussian mixture model.
    num_targ_pts : int  (N)
        Number of target points.
    num_src_pts : int  (M)
        Number of source points.
    dimensionality : int (D)
        Dimensionality of source and target points.
    iteration : int
        Current iteration.
    max_iterations : int
        Maximum number of iterations. default: 30
    tolerance : float
        Tolerance for convergence.
    w : float
        Contribution of the uniform distribution.
    q : float
        Objective function value.
    diff : float
        Difference between consecutive objective function values.
    probs : torch.Tensor    (P)
        MxN array of probabilities.
    sum_probs_x : torch.Tensor  (Pt1)
        Nx1 array, sum of probabilities for each target point.
    sum_probs_y : torch.Tensor     (Ps1??)
        Mx1 array, sum of probabilities for each source point.
    sum_probs : float
        Sum of all probabilities.
    probs_x : torch.Tensor
        MxD array, probs @ targets
    """

    def __init__(
        self,
        x,
        y,
        sigma2=None,
        max_iterations=None,
        tolerance=None,
        w=None,
        *args,
        **kwargs,
    ):
        """
        Initialize the ExpMaxRegistration class.
        """
        if x.ndim != 2:
            raise ValueError("The target point cloud (target) must be a 2D array.")

        if y.ndim != 2:
            raise ValueError("The source point cloud (source) must be a 2D array.")

        if x.shape[1] != y.shape[1]:
            raise ValueError("Both point clouds need to have the same number of dimensions.")

        if sigma2 is not None and sigma2 <= 0:
            raise ValueError(f"Expected a positive value for sigma2 instead got: {sigma2}")

        if max_iterations is not None and max_iterations < 0:
            raise ValueError(f"Expected a positive integer for max_iterations instead got: {max_iterations}")
        elif not isinstance(max_iterations, int) and max_iterations is not None:
            max_iterations = int(max_iterations)

        if tolerance is not None and tolerance < 0:
            raise ValueError(f"Expected a positive float for tolerance instead got: {tolerance}")

        if w is not None and (w < 0 or w >= 1):
            raise ValueError(f"Expected a value between 0 (inclusive) and 1 (exclusive) for w instead got: {w}")

        # "We consider the points in Y as the GMM centroids, and the points in X as the data points generated by the GMM. "
        self.x = x
        self.y = y
        self.fact = {"dtype": x.dtype, "device": x.device}
        self.transformed_y = y.clone()
        self.sigma2 = self.initialize_sigma2(x, y) if sigma2 is None else sigma2
        (self.num_targ_pts, self.dimensionality) = self.x.shape
        self.num_src_pts = self.y.shape[0]
        self.tolerance = 1e-3 if tolerance is None else tolerance
        self.w = 0.0 if w is None else w
        self.max_iterations = 30 if max_iterations is None else max_iterations
        self.iteration = 0
        self.diff = float("inf")
        self.q = float("inf")
        self.probs = torch.zeros((self.num_src_pts, self.num_targ_pts), **self.fact)
        self.sum_probs_x = torch.zeros((self.num_targ_pts,), **self.fact)
        self.sum_probs_y = torch.zeros((self.num_src_pts,), **self.fact)
        self.probs_x = torch.zeros((self.num_src_pts, self.dimensionality), **self.fact)
        self.sum_probs = 0

    def initialize_sigma2(self, target, source):
        """
        Initialize the variance (sigma2).

        Attributes
        ----------
        target: numpy array
            NxD array of points for target.

        source: numpy array
            MxD array of points for source.

        Returns
        -------
        sigma2: float
            Initial variance.
        """
        (num_targ_pts, dimensionality) = target.shape
        (num_src_pts, _) = source.shape
        diff = target[None, :, :] - source[:, None, :]
        err = torch.pow(diff, 2.0)
        return torch.sum(err) / (dimensionality * num_src_pts * num_targ_pts)

    def register(self, callback=lambda **kwargs: None):
        """
        Perform the EM registration.

        Attributes
        ----------
        callback: function
            A function that will be called after each iteration.
            Can be used to visualize the registration process.

        Returns
        -------
        self.transformed_y: numpy array
            MxD array of transformed source points.

        registration_parameters:
            Returned params dependent on registration method used.
        """
        self.transform_point_cloud()
        while self.iteration < self.max_iterations and self.diff > self.tolerance:
            self.iterate()
            if callable(callback):
                kwargs = {
                    "iteration": self.iteration,
                    "error": self.q,
                    "target": self.x,
                    "source": self.transformed_y,
                }
                callback(**kwargs)
            print(f"{self.iteration}: diff = {self.diff}, error = {self.q}")

        return self.transformed_y, self.get_registration_parameters()

    def get_registration_parameters(self):
        """
        Placeholder for child classes.
        """
        raise NotImplementedError("Registration parameters should be defined in child classes.")

    def update_transform(self):
        """
        Placeholder for child classes.
        """
        raise NotImplementedError("Updating transform parameters should be defined in child classes.")

    def transform_point_cloud(self):
        """
        Placeholder for child classes.
        """
        raise NotImplementedError("Updating the source point cloud should be defined in child classes.")

    def update_variance(self):
        """
        Placeholder for child classes.
        """
        raise NotImplementedError(
            "Updating the Gaussian variance for the mixture model should be defined in child classes."
        )

    def iterate(self):
        """
        Perform one iteration of the EM algorithm.
        """
        self.expectation()
        self.maximization()
        self.iteration += 1

    def expectation(self):
        """
        Compute the expectation step of the EM algorithm.
        """
        probs = torch.sum(
            (self.x[None, :, :] - self.transformed_y[:, None, :]) ** 2, axis=2
        )  # (num_src_pts, num_targ_pts)
        probs = torch.exp(-probs / (2 * self.sigma2))
        c = (
            (2 * torch.pi * self.sigma2) ** (self.dimensionality / 2)
            * self.w
            / (1.0 - self.w)
            * self.num_src_pts
            / self.num_targ_pts
        )

        den = torch.sum(probs, axis=0, keepdims=True)  # (1, num_targ_pts)
        den = torch.clip(den, torch.finfo(self.x.dtype).eps, None) + c
        self.probs = torch.divide(probs, den)
        self.sum_probs_x = torch.sum(self.probs, axis=0)
        self.sum_probs_y = torch.sum(self.probs, axis=1)
        self.sum_probs = torch.sum(self.sum_probs_y)
        self.probs_x = torch.matmul(self.probs, self.x)

    def maximization(self):
        """
        Compute the maximization step of the EM algorithm.
        """
        self.update_transform()
        self.transform_point_cloud()
        self.update_variance()

    # def p_step(self):
