#!/bin/bash
# One-time GPU venv build for zReg on a JSC **JUPITER** login node (GH200 / aarch64).
#
#     ssh jupiter 'bash /e/project1/tissuetwin/herold2/jsc-mpc-runs/zreg-jupiter/scripts/jupiter/cluster_provision_jupiter.sh'
#
# Mirrors steghn-sbi's proven pattern: the venv lives OUTSIDE the synced work tree (the jsc-mpc
# sync refuses a dirty cluster checkout), torch comes from the JSC PyTorch module (matches the
# GH200 driver stack), and an env file records the exact module lines so job scripts source ONE
# file. Login nodes have internet but no GPU; the job script checks torch.cuda.is_available().
#
# Paths are on JUPITER's own ExaSTORE (/e/...). The JUST filesystems (/p/...) are mounted on
# login nodes only, so a venv or checkout there is invisible to every compute job.
set -euo pipefail

ROOT="${ZREG_CLUSTER_ROOT:-/e/project1/tissuetwin/herold2/jsc-mpc-runs}"
VENV="${ZREG_VENV:-$ROOT/venvs/zreg-jupiter}"
ENV_SH="${ZREG_ENV_SH:-$ROOT/venvs/zreg-jupiter.env.sh}"
SRC="${ZREG_CLUSTER_SRC:-$ROOT/zreg-jupiter}"
STAGE="${ZREG_STAGE:-2026}"
TORCH_MODULE="${ZREG_TORCH_MODULE:-PyTorch/2.9.1}"

echo "[provision] root=$ROOT venv=$VENV src=$SRC stage=$STAGE torch=$TORCH_MODULE"

if ! type -t module >/dev/null 2>&1; then
    # shellcheck disable=SC1090
    source "${BASH_ENV:-/e/software/default/lmod/lmod/init/bash}"
fi
# Lmod is hierarchical and a multi-module load can fail silently, so load one level at a time.
ml_load() { set +eu; module load "$@"; local rc=$?; set -eu; return $rc; }

set +eu; module purge; set -eu
MODULE_CMDS="module purge"
for m in "Stages/${STAGE}" GCC ParaStationMPI Python SciPy-bundle "${TORCH_MODULE}" mpi4py; do
    ml_load "$m"
    MODULE_CMDS="${MODULE_CMDS}
module load ${m}"
done
python3 -c "import torch, sys; sys.exit(0 if torch.version.cuda else 1)" || {
    echo "ERROR: $TORCH_MODULE has no CUDA build. Try: module spider PyTorch" >&2; exit 1; }
echo "[provision] torch $(python3 -c 'import torch;print(torch.__version__, "| CUDA", torch.version.cuda)')"

if [ -x "$VENV/bin/python" ]; then
    echo "[provision] venv already present: $VENV (idempotent skip of base build)"
else
    mkdir -p "$(dirname "$VENV")"
    # --system-site-packages: torch, numpy, scipy, pandas, mpi4py come from the module layer.
    python3 -m venv --system-site-packages "$VENV"
    "$VENV/bin/pip" install --upgrade pip
    "$VENV/bin/pip" install colorlog tqdm "pydantic>=2.10,<3" "pyyaml>=6.0,<7" matplotlib \
        "optuna>=4.0,<5" torch_geometric scikit-learn pytest pytest-timeout
    # open3d is a declared dependency but has no wheel for every Python/aarch64 combination.
    # zReg imports it lazily, so a missing open3d only skips the Open3D-backed tests.
    "$VENV/bin/pip" install open3d || echo "[provision] WARNING: open3d unavailable here — Open3D tests will skip"
    # propulate pins GPy~=1.13.1, which pins scipy<=1.12 and makes pip build that old scipy from
    # source (fails on aarch64). Install both without dependency resolution so the module scipy is
    # kept, and compile GPy against the module numpy: the published GPy wheel targets another numpy ABI.
    "$VENV/bin/pip" install deepdiff h5py paramz cython
    if "$VENV/bin/pip" install --no-cache-dir --no-deps --no-build-isolation --no-binary GPy "GPy~=1.13.1" \
        && "$VENV/bin/pip" install --no-deps "propulate>=1.0,<2" \
        && "$VENV/bin/python" -c "import propulate"; then
        echo "[provision] propulate installed (GPy built from source against module numpy)"
    else
        "$VENV/bin/pip" uninstall -y propulate GPy || true
        echo "[provision] WARNING: propulate unavailable — Propulate tests will skip"
    fi
fi

# Editable install without dependency resolution: the module layer already provides torch etc.,
# and resolving open3d again would fail where no wheel exists.
if [ -d "$SRC" ]; then
    "$VENV/bin/pip" install --no-deps -e "$SRC"
    echo "[provision] editable install of $SRC"
else
    echo "WARNING: checkout not found at $SRC — run jsc-mpc sync_code first, then re-run." >&2
fi

cat > "$ENV_SH" <<ENVEOF
# Generated by scripts/jupiter/cluster_provision_jupiter.sh — source this in job scripts.
# Lmod and venv/bin/activate reference unset variables, so the caller's -e/-u flags are saved,
# relaxed here, and restored at the end. (\$- is read in this shell: "\$(set +o)" would run in a
# command substitution, where bash clears errexit, and restoring that would disable set -e.)
_zreg_saved_flags="\$-"
set +eu
type -t module >/dev/null 2>&1 || source "\${BASH_ENV:-/e/software/default/lmod/lmod/init/bash}"
${MODULE_CMDS}
source "${VENV}/bin/activate"
case "\$_zreg_saved_flags" in *e*) set -e ;; esac
case "\$_zreg_saved_flags" in *u*) set -u ;; esac
unset _zreg_saved_flags
ENVEOF
echo "[provision] wrote env file: $ENV_SH"

"$VENV/bin/python" - <<'PY'
import torch, pydantic, optuna, yaml, matplotlib, torch_geometric
import zreg
print("venv ok: torch", torch.__version__, "| cuda build", torch.version.cuda,
      "| pydantic", pydantic.__version__, "| optuna", optuna.__version__)
PY
echo "[provision] done. Job scripts should: source $ENV_SH"
