data_path: data/external/sample/kobitski_data/12_11_15_embryo_ew_06_Cleaned_BackTracked_Oriented.tracklets
data_format: tracklets
tier: dev
n_trials: 10
n_synthetic: 50
run_alignment: true
run_label_transfer: false
default_params:
  window_size: 10
  step: 1
  cpd_penalty: null
  dtw_dist_fn: euclidean
  n_breakpoints: 5
